unique_ids:
  assets:
    standard-page.html: 3LGQ4AT5FU5DC72EE7I4V62ANGTVSPXW
    theme.css: WL2E53QSL5P43ZKTUND3E4KHFUYCD6RH
  forms: {}
  modules:
    Form1: TOAATGDD27TU3SW73C2AVT3GS5KIR3JB
    Form1.ItemTemplate1: R56ZDD6JT6QQ2NTW4KCV4WV23LI54QYZ
    Form1.ItemTemplate1._template: 5DCXUZMWCNJCCSLHT5DCACNFSCE26LVC
    Form1._template: GW3KILTDMRLTOY2LGY6RG6CAZLEYCWZL
  scripts: {}
  server_modules:
    ServerModule1: KPNC5XPQSXSSQO5FHHW6LXXLP247VKL3
    ServerModule2: XH2LXNJWIUMPY7R5IOQNIVCCVMCTAIMF
